### ISSUE TITLE
Question about the approach

### ISSUE THREAD

**Issue by arademaker** [michmech/plausibility#1]
The ideia is nice , but how do you compose the filtering with a complete process of parsing followed by generation ?

**Comment by michmech** [comment]
I guess the short answer to that question is you don't. Plausibility
filtering is (mainly) only relevant if you're using the grammar for random
generation. If you're using the grammar for translation, then it's probably
safe to assume the sentence is plausible (to the user who is asking for the
translation) and ignore the plausibility filter. In other words: if they're
asking for a translation of 'this very Italian pizza is very Italian', by
all means, give it to them!

The only time when plausibility filtering could be relevant in the
translation scenario is when the user asks the grammar to translate a
sentence, and the sentence parses into more than one abstract syntax tree,
some of which are plausible and others not. Then you could use the
linearization output of the plausibility filter to rank/order the
translations. This is something you would have to organize outside of GF
though, as there is no in-built support for plausibility filtering in
either of the two GF runtimes. Yet! :-)

M.

Am Fr., 14. Dez. 2018, 22:01 hat Alexandre Rademaker <
notifications@github.com> geschrieben:
